// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxJZgiA_uxjGmJ7oylT6IHJ2L7bi7cfQE',
    appId: '1:445936331172:web:d4b169e579c452cda87931',
    messagingSenderId: '445936331172',
    projectId: 'learn-driving-1ad82',
    authDomain: 'learn-driving-1ad82.firebaseapp.com',
    storageBucket: 'learn-driving-1ad82.firebasestorage.app',
    measurementId: 'G-3HTW0PNJLS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB5SwhU6HikLms-2pZnYUHYPX66UT_CrU',
    appId: '1:445936331172:android:67708d8cd84f5237a87931',
    messagingSenderId: '445936331172',
    projectId: 'learn-driving-1ad82',
    storageBucket: 'learn-driving-1ad82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9HYBeIsdOFXyHjTZV-WibUuA8L042K8s',
    appId: '1:445936331172:ios:3dd725a5fbfd805ba87931',
    messagingSenderId: '445936331172',
    projectId: 'learn-driving-1ad82',
    storageBucket: 'learn-driving-1ad82.firebasestorage.app',
    iosBundleId: 'com.example.learnDriving',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9HYBeIsdOFXyHjTZV-WibUuA8L042K8s',
    appId: '1:445936331172:ios:3dd725a5fbfd805ba87931',
    messagingSenderId: '445936331172',
    projectId: 'learn-driving-1ad82',
    storageBucket: 'learn-driving-1ad82.firebasestorage.app',
    iosBundleId: 'com.example.learnDriving',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxJZgiA_uxjGmJ7oylT6IHJ2L7bi7cfQE',
    appId: '1:445936331172:web:84be3237ce0660a0a87931',
    messagingSenderId: '445936331172',
    projectId: 'learn-driving-1ad82',
    authDomain: 'learn-driving-1ad82.firebaseapp.com',
    storageBucket: 'learn-driving-1ad82.firebasestorage.app',
    measurementId: 'G-4VNHKQZF47',
  );
}
